/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>

#define PLUGIN "New Plug-In"
#define VERSION "1.0"
#define AUTHOR "author"


public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	register_clcmd("say", "handle_say")
}

public handle_say(id){
	new said[192];
	read_args(said, 191)
	if( (containi(said, "/vipinfo") != -1) )
		show_motd(id, "Ultimate_VipInfo.txt")
}